imports:
    - php

filter:
    excluded_paths: [vendor/*, tests/*]

build:
    image: default-bionic

    dependencies:
        override:
            -   command: "npm rebuild"
            -   command: "npm install"
                idle_timeout: "180"

    nodes:
        my-tests:
            environment:
                php:
                    version: 8.3.3
                    # version: 8.3.3
                    # version: 8.1.17
                    #version: 8.2.4
        analysis:
            tests:
                override:
                    - php-scrutinizer-run
    tests:
        override:
            -   command: "composer phpunit"
                # command: "XDEBUG_MODE=coverage vendor/bin/phpunit"
                coverage:
                    file: "docs/coverage.clover"
                    format: "php-clover"